spring:
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service-users
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthentication

        - id: course-service-read
          uri: http://course-service:8082
          predicates:
            - Path=/api/courses/**
            - Method=GET
          filters:
            - name: JwtAuthentication

        - id: course-service-write
          uri: http://course-service:8082
          predicates:
            - Path=/api/courses/**
            - Method=POST,PUT,DELETE
          filters:
            - name: JwtAuthentication
              args:
                requiredRoles:
                  - ROLE_INSTRUCTOR
                  - ROLE_ADMIN

        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/api/enrollments/**
          filters:
            - name: JwtAuthentication

        - id: notification-service
          uri: http://notification-service:8084
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtAuthentication

        - id: progress-service
          uri: http://progress-service:8085
          predicates:
            - Path=/api/progress/**
          filters:
            - name: JwtAuthentication

        - id: media-service
          uri: http://media-service:8086
          predicates:
            - Path=/api/media/**
          filters:
            - name: JwtAuthentication

        - id: assessment-service
          uri: http://assessment-service:8087
          predicates:
            - Path=/api/assessments/**
          filters:
            - name: JwtAuthentication

        - id: quiz-student-service
          uri: http://assessment-service:8087
          predicates:
            - Path=/api/quizzes/**
          filters:
            - name: JwtAuthentication

downstream:
  health-check:
    interval-ms: 15000
    services:
      user-service:         http://user-service:8081
      course-service:       http://course-service:8082
      enrollment-service:   http://enrollment-service:8083
      notification-service: http://notification-service:8084
      progress-service:     http://progress-service:8085
      media-service:        http://media-service:8086
      assessment-service:   http://assessment-service:8087

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans